name: Update devContainer prebuilt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - uses: docker/setup-buildx-action@v3
        - uses: docker/build-push-action@v5
          with:
            push: true
            tags: sacnussem/devcontainer:orb_slam2
            context: '{{defaultContext}}:.devcontainer'
        - run: |
            npm install -g @devcontainers/cli
            devcontainer build --config .devcontainer/prebuilt.json --workspace-folder . --push true --image-name sacnussem/devcontainer:orb_slam2-prebuilt
